upstream backend_servers {
    server app_instance_a:5000 max_fails=1 fail_timeout=2s;
    server app_instance_b:5000 max_fails=1 fail_timeout=2s;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
